### ISSUE TITLE
Mention original author as well as last update author

### ISSUE THREAD

**Issue by aaruni96** [desmond27/DigitForumBot#9]
Currently, the bot mentions only the "latest author" on a forum post. This can get misleading, for example :

```
[For Sale] AMD Ryzen 5 2600 Processor
by Desmond
```
Instead, we should mention who the post is originally from in addition to who made the last message. Maybe something like

```
[For Sale] AMD Ryzen 5 2600 Processor by chetansha
last updated by Desmond
```

**Comment by desmond27** [comment]
Makes sense, though it's feels too crowded which is why I decided not to go with it.
